### ISSUE TITLE
Marcar tratados 4, 6 y 7, y el prólogo

### ISSUE THREAD

**Issue by ajleon95** [susannalles/MinimalEditions#13]
Ya que nos hemos puesto de acuerdo con una esquema para el markup, nos falta todavía marcar el prólogo y tratados 4, 6 y 7. 

Yo me puedo encargar de marcar el prólogo y el tratado 4 esta semana, si alguien quiere hacer seis o siete.

**Comment by rmania1** [comment]
Yo haré el tratado 7.

**Comment by ajleon95** [comment]
Muchas gracias Taewan, te marco como asignado también para que así podemos ver quien se encarga de quien en la página de Issues.

**Comment by ajleon95** [comment]
OK nvm solo se puede marcar una persona como asignado asi nos encargamos de este Issue juntos con alguien más que puede hacer el 6

**Comment by marykennedy** [comment]
Yo puedo marcar el tratado 6.

**Comment by ajleon95** [comment]
Mil gracias a todos, como yo ya he terminado con el prólogo y tratado 4, voy a asignar esto a Falls así que puede continuar con el trabajo. Por favor vean mi marcado para ver que todo este bien -- pienso que si lo es pero es posible que se me olvidó algo

**Comment by rmania1** [comment]
Acabo de terminar el tratado 7.

**Comment by ajleon95** [comment]
Mil gracias Taewan

**Comment by ajleon95** [comment]
Hola @marykennedy, todo va bien con el tratado 6?

**Comment by marykennedy** [comment]
Sí, pensé que añadía a GitHub ¿pero aparece en su proyecto?

**Comment by ajleon95** [comment]
Gracias Falls, ya todo completo. 👍
