### ISSUE TITLE
Highlighting Lazarillo's masters

### ISSUE THREAD

**Issue by rmania1** [susannalles/MinimalEditions#4]
Each chapter of Lazarillo, he has a different master. I find it to be crucial to somehow highlight the master's name/occupation/description when he appears for the first time in the chapter to facilitate the reading.

**Comment by susannalles** [comment]
Esto deberíamos discutirlo cómo hacerlo exactamente.

**Comment by rmania1** [comment]
Creo que ya decimos cuales son las cosas que debemos marcar cuando hablamos de los amos. Por lo tanto, cierro este issue.
