### ISSUE TITLE
Reconcile divs

### ISSUE THREAD

**Issue by fak2119** [susannalles/MinimalEditions#6]
Decide how we are dividing it up

**Comment by ajleon95** [comment]
For mine, I put my entire tratado in `<div type="tratado">` and put the header/subheader in `title` tags. But I saw you put the title and text in different `div`s. Which do you think is better?

**Comment by ajleon95** [comment]
I've went ahead and made some changes: 
1. I separated the title and subtitle section and the text section into two different divs with types titulo and texto. 
2. I gave each `texto` div a unique ID
3. I gave each `titulo` div a corresp that points to the ID of `texto`.

I hope that this solution works.

**Comment by elotroalex** [comment]
Todos tomamos turnos para cambiar los divs (en castellano: divisiones).
