### ISSUE TITLE
Is God a character?

### ISSUE THREAD

**Issue by ajleon95** [susannalles/MinimalEditions#7]
Me and Falls marked up each mention of God as a particular character or named person. Should we continue this, or remove the `persName` tags for God?

**Comment by rmania1** [comment]
I say, we remove the `persName` tags for God

**Comment by susannalles** [comment]
Sí, yo también creo que "Dios" no es un personaje. Normalmente aparece en expresiones y frases hechas, no tiene por tanto un papel en la obra como tal.

**Comment by ajleon95** [comment]
To write what I did: I replaced all `persName corresp="#Dios"` with `name type="religious" corresp="#Dios"`. For the first instance of Dios I made it `name type="religious" xml:id="Dios"`.
