### ISSUE TITLE
Marking up pronouns

### ISSUE THREAD

**Issue by ajleon95** [susannalles/MinimalEditions#8]
I marked down pronouns (él, aquel, etc.) using `persName` tags, but was wondering if this might be appropriate for our project. What do you all think?

**Comment by fak2119** [comment]
I was thinking about function when I was marking and decided not to. It might have been a better idea to discuss our different proposals for the interface and what we want our digital edition to actually look like and do (Tarea 2) before each going off to do our own thing. I think we should first all discuss and decide on what we want the edition to be, and then make this decision based on how functional it would be.

**Comment by ajleon95** [comment]
Sounds good, I'll clean up my part right now and push the changes.

**Comment by ajleon95** [comment]
Okay, I've gone ahead and removed the markup from pronouns (él, aquel, éste, etc.) (though not terms of endearment which is another ongoing convo). I think we can now close the issue.
